apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zq-gh-action-flow
  labels:
    app.kubernetes.io/name: zq-gh-action-flow
    app.kubernetes.io/part-of: zq-gh-action-flow-project
    kubernetes.azure.com/generator: devhub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zq-gh-action-flow
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80