apiVersion: v1
kind: Service
metadata:
  name: zq-gh-action-flow
  namespace: contoso-air-ns
  labels:
    app.kubernetes.io/name: zq-gh-action-flow
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: zq-gh-action-flow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000